### ISSUE TITLE
Invalid Free

### ISSUE THREAD

**Issue by firetwister** [ghaderer/libmicrohttpd#1]
The documentation for [SSL_CTX_add_extra_chain_cert](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_add_extra_chain_cert.html) states not to free the x509 object, like it's done at the end of the MHD_TLS_openssl_set_context_trust_certificate function.

**Comment by ghaderer** [comment]
You're absolutely right. I'll fix that. Thanks for pointing out!

**Comment by ghaderer** [comment]
Fixed in 065fc28203ebae6d6c27c1b0f6e8ea79e466597c.
