### ISSUE TITLE
Initialization for client certificate verification in openssl - session id context

### ISSUE THREAD

**Issue by rokonrad** [ghaderer/libmicrohttpd#4]
When implementing server-side client certificate authentication in openssl using MHD_OPTION_HTTPS_MEM_TRUST the tls handshake always fails with the error message 
"session id context uninitialized".
[openSSL wiki](https://wiki.openssl.org/index.php/Manual:SSL_CTX_set_session_id_context(3)) has a warning:
`If the session id context is not set on an SSL/TLS server and client certificates are used, stored sessions will not be reused but a fatal error will be flagged and the handshake will fail.`

When I add SSL_CTX_set_session_id_context() to MHD_TLS_openssl_set_context_trust_certificate this error is gone. For testing purposes I hacked in a temporary string, but maybe one could also think about using some kind of random bytes, e.g. RAND_pseudo_bytes()?

**Comment by ghaderer** [comment]
Hello,

How do you reproduce this issue?

**Comment by rokonrad** [comment]
Without having verified it I think one has to ensure the handshake fails for another reason so that the client tries to connect again (usually browsers seem to have some kind of retry counter > 0) as this error comes up if a stored session would normally been reused.
But as I said, I haven't verified it yet with your last commits.

**Comment by rokonrad** [comment]
When I set a CA for client authentication (trust mem), connect via HTTPS and send a valid client certificate so that verification succeeds (without setting the session id context) I got the following debug output:

`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_session_handshake: SSL_accept: 0, SSL_get_error: 5`
`Session handshake failed, errno: Success (0)`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_session_handshake: SSL_accept: 0, SSL_get_error: 5`
`Session handshake failed, errno: Success (0)`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_session_handshake: SSL_accept: 0, SSL_get_error: 5`
`Session handshake failed, errno: Success (0)`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_verify_callback: preverify_ok 1`
`MHD_TLS_openssl_verify_callback: preverify_ok 1`
`MHD_TLS_openssl_session_handshake: SSL_accept: 1, SSL_get_error: 0`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_verify_callback: preverify_ok 1`
`MHD_TLS_openssl_verify_callback: preverify_ok 1`
`MHD_TLS_openssl_session_handshake: SSL_accept: 1, SSL_get_error: 0`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 1`
`Session handshake failed, errno: Success (0)`
`Session handshake failed, SSL_get_error: 1, ERR_get_error: error:140D9115:SSL routines:ssl_get_prev_session:session id context uninitialized (336433429)`
`Session close failed: 1`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 1`
`Session handshake failed, errno: Success (0)`
`Session handshake failed, SSL_get_error: 1, ERR_get_error: error:140D9115:SSL routines:ssl_get_prev_session:session id context uninitialized (336433429)`

SSL_get_error:
0 SSL_ERROR_NONE
1 SSL_ERROR_SSL
2 SSL_ERROR_WANT_READ
5 SSL_ERROR_SYSCALL

This is without doing any hacks to let the TLS handshake fail in the first step.

As you can see I use the verify_callback here. Strange is that the callback is called so many times.
Also strange are the SSL_ERROR_SYSCALL errors where errno is 0 (Success), maybe some kill signals from anywhere?

When I set the session id context the logs looks like this:
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_session_handshake: SSL_accept: 0, SSL_get_error: 5`
`Session handshake failed, errno: Success (0)`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_session_handshake: SSL_accept: 0, SSL_get_error: 5`
`Session handshake failed, errno: Success (0)`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_session_handshake: SSL_accept: 0, SSL_get_error: 5`
`Session handshake failed, errno: Success (0)`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_verify_callback: preverify_ok 1`
`MHD_TLS_openssl_verify_callback: preverify_ok 1`
`MHD_TLS_openssl_session_handshake: SSL_accept: 1, SSL_get_error: 0`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_verify_callback: preverify_ok 1`
`MHD_TLS_openssl_verify_callback: preverify_ok 1`
`MHD_TLS_openssl_session_handshake: SSL_accept: 1, SSL_get_error: 0`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_session_handshake: SSL_accept: 1, SSL_get_error: 0`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_session_handshake: SSL_accept: 1, SSL_get_error: 0`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_session_handshake: SSL_accept: 1, SSL_get_error: 0`
`MHD_TLS_openssl_session_handshake: SSL_accept: -1, SSL_get_error: 2`
`MHD_TLS_openssl_session_handshake: SSL_accept: 1, SSL_get_error: 0`

Hope this helps!

**Comment by ghaderer** [comment]
Could you send the procedure you use to reproduce this defect? With the code at commit 5c52f9ad8e92921d7329487ade99a912578ec055, I can succesfully connect using client authentication.

Could you tell me which client you use? If you have a simple program to reproduce this issue, that would help a lot. Thanks!

**Comment by rokonrad** [comment]
I'm compiling under gentoo in an lxc container with crossdev for arm platform.
I'll try if I can reproduce it on the host system x86.

**Comment by rokonrad** [comment]
My implementation was missing the MHD_OPTION_TLS_ENGINE_TYPE option so I thought it could have something to do with the session id context error.

Unfortunately not, will have to dig deeper.

**Comment by rokonrad** [comment]
Fixed in [2750358](https://github.com/rokonrad/libmicrohttpd/commit/2750358cdc38b0746bb43595af9830c42bcc44c8)
:-)
